### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by evosex** [j26design/Ecwid-Store-Designer#10]
Hi

I want to have my background in black. But when i do only parts of the page is black, the rest is still white. is that possible to change?

BR Andreas

**Comment by jp26jp** [comment]
Yes, can you send me the URL of your store?

**Comment by evosex** [comment]
Hi

braceletyourself.ecwid.com


Mvh Andreas

**Comment by jp26jp** [comment]
Okay, give it a try now!

**Comment by jp26jp** [comment]
You might have to clear your cache for it to work.

**Comment by evosex** [comment]
Hi
Thanks now it works

Mvh Andreas

> 4 dec. 2019 kl. 16:04 skrev John R Perry <notifications@github.com>:
> 
> ﻿Okay, give it a try now!
>
