### ISSUE TITLE
[ IMPORTANT ] Not able to re-install

### ISSUE THREAD

**Issue by vignisson** [j26design/Ecwid-Store-Designer#11]
Hi, 

Thanks for great app!!  I installed it and redesigned my store quite a bit on the trial period. I have now launched my store but the subscription payment for the Store Designer failed and therefor it was deactivated.  Now when I try to install it again and pay the subscription it just shows a spinner and nothing happens. 

request #1:  Since my store is currently live I need to get the Store Designer up ASAP!

request #2: It would be great to get some notice regarding unsuccessful payment (if that's on your side). Then given 24-48 hours to solve it before the app is deactivated.

All the best!

Egill Vignisson

**Comment by jp26jp** [comment]
I've included Ecwid support in this thread so we can figure out what
happened

**Comment by vignisson** [comment]
Thanks for you extremely quick response yesterday! However, nothing seems
to be fixed and I even waited on Ecwids Support Chat but received no
response either. Can you please give it a second look?

Thanks!

Egill
