### ISSUE TITLE
has NEVER loaded, always fails. really why F***king bother.. 

### ISSUE THREAD

**Issue by getafixx** [j26design/Ecwid-Store-Designer#12]
Something went wrong
Requested extension cannot be loaded. Please try to refresh this page.

If the problem persists, please contact the authors of “Store Designer” extension at www.j-26.com/app-docs/ecwid/store-designer/

Uninstalling...

**Comment by jp26jp** [comment]
No one has ever had this issue and since you're uninstalling the app, I have no way to be of assistance.
