### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by vivbkt** [j26design/Ecwid-Store-Designer#5]
hi, it's not loading
![screen shot 2018-10-25 at 6 06 14 pm](https://user-images.githubusercontent.com/10008823/47492937-b3dfc400-d880-11e8-9caf-19c710edaa17.png)

**Comment by jp26jp** [comment]
I'm so sorry for the hiccup but it should be working again!

**Comment by vivbkt** [comment]
it's down again :(

are you even taking this seriously ?

**Comment by jp26jp** [comment]
I just checked and it's not down. I'm obviously taking it seriously as I resolved the issue the day you brought it to my attention.

**Comment by vivbkt** [comment]
It’s back on after few refreshes
