### ISSUE TITLE
Radio Button Styling Request...

### ISSUE THREAD

**Issue by zerogravitymedia** [j26design/Ecwid-Store-Designer#6]
Can you please add this to the control panel? 

Thank you :)

**Comment by jp26jp** [comment]
Sure! What kind of styling were you thinking? Like color change?

**Comment by zerogravitymedia** [comment]
Yes!
I see that you added in the designer.
Thats a Great start!!!

I want to be able to change the “unchecked” state of the radio button to thicker or thinner border (kind of like when they are actually selected)
My current site has black background and the thin white radial selectors are hard to see before you click them.

Hope that makes sense.

:)

**Comment by jp26jp** [comment]
Ohh I see. Okay, I should be able to add what you're wanting within the next 24 hours!
